### ISSUE TITLE
Backend module shows no icons

### ISSUE THREAD

**Issue by beardcoder** [die-wegmeister/Wegmeister.DatabaseStorage#2]
No Icons are Visible in the Backend Module
![Image of backend module](https://preview.ibb.co/icFfOy/Bildschirmfoto_2018_05_17_um_21_21_43.png)

System: Neos 4

**Comment by Benjamin-K** [comment]
Thanks for reporting this. I currently do not have any Neos 4 installation for testing. I will take a look at this in about two weeks. If you know how to fix this, feel free to create a pull request.

**Comment by beardcoder** [comment]
Oki thx. I will try

**Comment by beardcoder** [comment]
![FIXED IMAGE](https://preview.ibb.co/f2N91T/Bildschirmfoto_2018_05_19_um_11_17_51.png)
