### ISSUE TITLE
Export returns error

### ISSUE THREAD

**Issue by beardcoder** [die-wegmeister/Wegmeister.DatabaseStorage#3]
Exception in line 206 of /app/Packages/Libraries/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Style/Style.php: Invalid cell coordinate A[1

**Comment by Benjamin-K** [comment]
This should be fixed with release [1.0.7](https://github.com/die-wegmeister/Wegmeister.DatabaseStorage/releases/tag/1.0.7)
