### ISSUE TITLE
Exclude form elements from export

### ISSUE THREAD

**Issue by Benjamin-K** [die-wegmeister/Wegmeister.DatabaseStorage#7]
Some form elements should not be included in the storage. Form elements that should not be included as they do not change the entry or contain sensitive data: 

- StaticText
- Password / PasswordWithConfirmation
- HiddenField
- Checkbox (sometimes, otherwise check how to set a default value to always have a column for checkbox fields)
- Section
- ...

Starting point: https://github.com/beardcoder/Wegmeister.DatabaseStorage/commit/2a271b40eea9231e63d7f02f9041db5d4acb27c3

**Comment by lorenzulrich** [comment]
We could debate if `nodeTypesIgnoredInExport` should already be applied in the Finisher, so such values are not even saved (certainly intersting for Password fields, if anyone uses this with DatabaseStorage). My implementation in #25 applies this on export.

**Comment by Benjamin-K** [comment]
I think both would be a great improvement. But especially for password fields, not even storing them should be the preferred way. So maybe we can add both options and add a `nodeTypesIgnoredFromStorage` setting. 

I can even think of a third setting for fields that should be optionally included in the export, sth. like `optionalNodeTypesInExport` (for example `HiddenField`s sometimes should be included, sometimes not). But this could also be added as a new feature.

**Comment by Benjamin-K** [comment]
Fixed with #25.
